jinac/urls.py
from django.contrib import admin
from django.urls import path, include
from django.utils.translation import gettext_lazy as _
from django.conf import settings
from django.conf.urls.static import static
from jinac.views import IndexView, SearchResultView, set_language, contact_message, markdown_uploader
from jinac.cases.views import CaseListView, CaseDetailView, TrialListView, TrialDetailView
from jinac.people.views import JournalistListView, JournalistDetailView
from jinac.articles.views import ArticleListView, ArticleDetailView, AboutView
from jinac.infographics.views import InfographicListView, InfographicDetailView


urlpatterns = [

    path('yonetim/', admin.site.urls),
    path('', IndexView.as_view(), name='index'),

    path('davalar/', CaseListView.as_view(), name='case_list'),
    path('davalar/<int:pk>/', CaseDetailView.as_view(), name='case_detail'),
    path('raporlar/', TrialListView.as_view(), name='trial_list'),
    path('davalar/<int:case>/<int:pk>/', TrialDetailView.as_view(), name='trial_detail'),

    path('gazeteciler/', JournalistListView.as_view(), name='journalist_list'),
    path('gazeteciler/<slug:slug>/', JournalistDetailView.as_view(), name='journalist_detail'),

    path('analizler/', ArticleListView.as_view(), name='article_list'),
    path('analizler/<slug:slug>/', ArticleDetailView.as_view(), name='article_detail'),
    path('rapor/', ArticleListView.as_view(), {'report': True}, name='report_list'),

    path('rapor/hapisteki-gazeteciler/', ArticleDetailView.as_view(), {
        'report': True,
        'slug': 'hapisteki-gazeteciler',
    }, name='report_jailed_journalists'),

    path('rapor/<slug:slug>/', ArticleDetailView.as_view(), {'report': True}, name='report_detail'),
    path('ne-yapiyoruz/', AboutView.as_view(), name='about'),

    path('infografik/', InfographicListView.as_view(), name='infographic_list'),
    path('infografik/<slug:slug>/', InfographicDetailView.as_view(), name='infographic_detail'),

    path('iletisim/', contact_message, name='contact_message'),

    path('lang/', set_language, name='set_lang'),

    path('martor/', include('martor.urls')),

    path('search/', include('haystack.urls')),

    path(
        'api/uploader/', markdown_uploader, name='markdown_uploader_page'
    ),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.index_title = _('Press in Arrest')
admin.site.site_header = _('Press in Arrest Administration')
admin.site.site_title = _('Press in Arrest Management')

jinac/cases/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.contrib.auth.models import User
from translations.models import Translatable
from django.template.defaultfilters import slugify
from martor.models import MartorField
from jinac.jurisdiction.models import Court
from jinac.people.models import Journalist, Judge, Prosecutor, Attorney, Plaintiff
from jinac.institutions.models import Institution, Observer


# case & trial decision types
DECISION_TYPES = (
    (0, _('acquittal')),
    (1, _('fine')),
    (2, _('imprisonment')),
    (6, _('postponed')),
    (7, _('judgement receded')),
    (8, _('discontinued')),
)


# cases

class Case(models.Model):
    name = models.CharField(_('case name'), max_length=250)
    name_en = models.CharField(_('case name (EN)'), max_length=250, blank=True, null=True)
    slug = models.SlugField(blank=True, null=True)
    no = models.CharField(_('file number'), max_length=20)
    court = models.ForeignKey(Court, verbose_name=_('court'), on_delete=models.CASCADE)
    filing_date = models.DateField(_('case filing date'), blank=True, null=True)  # iddianame tarihi
    opening_date = models.DateField(_('case opening date'), blank=True, null=True)  # dava acilis tarihi
    defendant_count = models.PositiveIntegerField(_('defendant count'), blank=True, null=True)
    journalist_defendant_count = models.PositiveIntegerField(_('journalist defendant count'), blank=True, null=True)
    coup_related = models.BooleanField(_('coup attempt related'), default=False)
    journalists = models.ManyToManyField(Journalist, through='CaseJournalist')
    plaintiff = models.ManyToManyField(Plaintiff, verbose_name=_('plaintiff'), blank=True)
    prosecutor = models.ForeignKey(Prosecutor, verbose_name=_('indictment prosecutor'),
                                   blank=True, null=True, on_delete=models.SET_NULL)
    summary = MartorField(_('case summary'), blank=True, null=True)
    summary_en = MartorField(_('case summary (EN)'), blank=True, null=True)
    order = models.PositiveSmallIntegerField(_('order'), default=0)

    related_cases = models.ManyToManyField('self', verbose_name=_('related cases'), blank=True)

    reporter = models.ForeignKey(User, verbose_name=_('reporter'), blank=True, null=True, on_delete=models.SET_NULL)
    publish = models.BooleanField(_('publish'), default=False)
    added = models.DateTimeField(_('added time'), auto_now_add=True)
    modified = models.DateTimeField(_('modified time'), auto_now=True)

    def __str__(self):
        return self.name

    def save(self, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(**kwargs)

    def get_absolute_url(self):
        return reverse('case_detail', args=[self.id])

    def status(self):
        return self.casestatus_set.last()

    def notes(self):
        return self.casenote_set.filter(type__publish=True).filter(journalist__isnull=True)

    def get_journalists(self):
        return self.journalists.filter(publish=True)

    class Meta:
        verbose_name = _('case')
        verbose_name_plural = _('cases')
        ordering = ('slug', 'order', '-modified',)


class CaseStatus(models.Model):
    case = models.ForeignKey(Case, verbose_name=_('case'), on_delete=models.CASCADE)
    status = models.PositiveSmallIntegerField(blank=True, choices=(
        (0, _('local')),
        (1, _('appeal')),
        (2, _('supreme',)),
        #(3, _('constitutional')),
        #(4, _('ECHR')),
        (5, _('abatement of action')),  # dusme
        (6, _('decision of reversal')),  # bozma
        (7, _('rejected')),  # reddedildi
    ))
    #date = models.DateField(blank=True, null=True)
    decision = models.PositiveSmallIntegerField(
        choices=(
            (1, _('approved')),
            (2, _('denied')),
        ), blank=True, null=True
    )
    details = models.TextField(_('details'), blank=True, null=True)

    def __str__(self):
        return self.get_status_display()

    class Meta:
        verbose_name = _('case status')
        verbose_name_plural = _('case status')
        #ordering = ('date',)


class WorkPosition(models.Model):
    position = models.CharField(_('work position'), max_length=100)

    def __str__(self):
        return self.position

    class Meta:
        verbose_name = _('work position')
        verbose_name_plural = _('work position')


class CaseJournalist(models.Model):
    case = models.ForeignKey('Case', verbose_name=_('case'), on_delete=models.SET_NULL, blank=True, null=True)
    journalist = models.ForeignKey(Journalist, verbose_name=_('journalists'), on_delete=models.CASCADE)
    institution = models.ForeignKey(
        Institution,
        verbose_name=_('institution'),
        blank=True, null=True,
        on_delete=models.SET_NULL,
    )
    position = models.ForeignKey(
        WorkPosition,
        verbose_name=_('work position'),
        blank=True, null=True, on_delete=models.SET_NULL
    )
    attorneys = models.ManyToManyField(Attorney, verbose_name=_('attorney'), blank=True)

    def __str__(self):
        return f"{self.case.__str__()} - {self.journalist.__str__()}"

    class Meta:
        verbose_name = _('case - journalist relation')
        verbose_name_plural = _('case - journalist relations')


class CaseDecision(models.Model):
    case = models.ForeignKey('Case', verbose_name=_('case'), on_delete=models.CASCADE)
    journalist = models.ForeignKey(Journalist, verbose_name=_('journalists'), on_delete=models.CASCADE)
    decision_type = models.PositiveSmallIntegerField(
        _('decision type'), blank=True, null=True,
        choices=DECISION_TYPES
    )
    articles = models.ManyToManyField('Article', verbose_name=_('articles'), blank=True)
    punishment_fine = models.CharField(_('fine'), max_length=100, blank=True, null=True)
    punishment_year = models.PositiveSmallIntegerField(_('year'), blank=True, null=True)
    punishment_month = models.PositiveSmallIntegerField(_('month'), blank=True, null=True)
    punishment_day = models.PositiveSmallIntegerField(_('day'), blank=True, null=True)
    punishment_life_sentence = models.PositiveSmallIntegerField(_('life sentence'), blank=True, null=True, choices=(
        (1, _('life sentence')),
        (2, _('aggravated life sentence')),
    ))

    def __str__(self):
        return f'{self.case.__str__()}'

    def get_punishment(self):
        if self.punishment_fine:
            return f'{self.punishment_fine} TL'
        else:
            punishment = []
            if self.punishment_year:
                punishment.append('%s %s' % (self.punishment_year, _('year')))
            if self.punishment_month:
                punishment.append('%s %s' % (self.punishment_month, _('month')))
            if self.punishment_day:
                punishment.append('%s %s' % (self.punishment_day, _('day')))
            return punishment and ', '.join(punishment) or '-'
    get_punishment.short_description = _('punishment')

    class Meta:
        verbose_name = _('case - decision relation')
        verbose_name_plural = _('case - decision relations')


class Article(models.Model):
    type = models.PositiveSmallIntegerField(choices=(
        (1, _('TCK')),
        (2, _('TMK')),
        #(3, _('Constitution')),
        (4, _('MİT')),
        (5, _('TGYK')),
        (6, _('Press Law')),
        (7, _('SPK')),
        (8, _('Banking Law')),
    ))
    description = models.TextField(_('article'), blank=True, null=True)
    indictment = models.CharField(_('indictment'), max_length=200, blank=True, null=True)
    no = models.CharField(max_length=20)
    punishment_type = models.PositiveSmallIntegerField(
        _('punishment type'), blank=True, null=True,
        choices=(
            (1, _('fine')),
            (2, _('imprisonment')),
        )
    )

    def __str__(self):
        return f"{self.get_type_display()} {self.no} {self.indictment}"

    class Meta:
        verbose_name = _('article')
        verbose_name_plural = _('articles')


class CaseIndictment(models.Model):
    case = models.ForeignKey('Case', verbose_name=_('case'), on_delete=models.CASCADE)
    journalist = models.ForeignKey(Journalist, verbose_name=_('journalist'), on_delete=models.CASCADE)
    articles = models.ManyToManyField(Article, verbose_name=_('articles'), blank=True)
    details = models.TextField(_('details'), blank=True, null=True)

    def __str__(self):
        return f'{self.case.__str__()}'

    class Meta:
        verbose_name = _('indictment')
        verbose_name_plural = _('indictments')


class CaseDocumentType(models.Model):
    type = models.CharField(_('type'), max_length=50)
    type_en = models.CharField(_('type'), max_length=50, blank=True, null=True)
    order = models.PositiveSmallIntegerField(_('order'), blank=True, null=True)

    def __str__(self):
        return self.type

    class Meta:
        verbose_name = _('case document type')
        verbose_name_plural = _('case document types')
        ordering = ('order', 'id')


class CaseDocument(models.Model):
    case = models.ForeignKey(Case, verbose_name=_('case'), on_delete=models.CASCADE)
    file = models.FileField(_('file'), upload_to='documents/')
    type = models.ForeignKey(CaseDocumentType, verbose_name=_('type'), blank=True, null=True, on_delete=models.SET_NULL)
    journalist = models.ForeignKey(Journalist, verbose_name=_('journalist'),
                                   blank=True, null=True, on_delete=models.SET_NULL)
    publish = models.BooleanField(_('publish'), default=False)

    def __str__(self):
        return f'{self.case.__str__()} - {self.file}'

    class Meta:
        verbose_name = _('case document')
        verbose_name_plural = _('case documents')
        ordering = ('case', 'type')


class CaseNoteType(models.Model):
    type = models.CharField(_('type'), max_length=100)

jinac/articles/views.py
from django.shortcuts import redirect
from django.utils.translation import get_language
from django.views.generic import ListView, DetailView, TemplateView
from jinac.articles.models import Article


class ArticleListView(ListView):
    model = Article

    def get_queryset(self):
        qs = super().get_queryset().filter(publish=True)
        qs = qs.exclude(about_page=True)
        if self.kwargs.get('report'):
            qs = qs.filter(type='r')
        else:
            qs = qs.filter(type='a')
        if self.request.LANGUAGE_CODE == 'en':
            qs = qs.filter(lang='en')
        else:
            qs = qs.filter(lang='tr')
        return qs


class ArticleDetailView(DetailView):
    model = Article

    def get_queryset(self):
        qs = super().get_queryset()
        #return qs.filter(publish=True)  # hapisteki gazeteciler listesini yayinlamadan gosterebilmek icin kaldirildi
        return qs

    def get(self, request, *args, **kwargs):
        article = self.get_object()
        if article.type == 'r' and not self.kwargs.get('report'):
            return redirect('report_detail', slug=article.slug)
        return super().get(request, *args, **kwargs)

    def get_object(self, queryset=None):
        article = super().get_object(queryset)
        if article.lang != get_language() and article.translation:
            return article.translation
        return article


class AboutView(TemplateView):
    template_name = 'articles/article_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        articles = Article.objects.filter(publish=True).filter(about_page=True)
        if self.request.LANGUAGE_CODE == 'en':
            articles = articles.filter(lang='en')
        else:
            articles = articles.filter(lang='tr')
        context.update({
            'article': articles.first()
        })
        return context

jinac/cases/views.py
from django.views.generic import ListView, DetailView
from jinac.cases.models import Case, Trial


class CaseListView(ListView):
    model = Case

    def get_queryset(self):
        qs = super().get_queryset().filter(publish=True)
        if self.request.GET.get('f'):
            qs = qs.filter(name__istartswith=self.request.GET.get('f'))
        return qs.filter(publish=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'filter': self.request.GET.get('f')
        })
        return context


class CaseDetailView(DetailView):
    model = Case

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(publish=True)


class TrialListView(ListView):
    model = Trial

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(publish=True).order_by('-time_start')


class TrialDetailView(DetailView):
    model = Trial

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(publish=True)

jinac/contact/views.py
from django.shortcuts import render

# Create your views here.

jinac/infographics/views.py
from django.views.generic import ListView, DetailView
from jinac.infographics.models import Infographic


class InfographicListView(ListView):
    model = Infographic

    def get_queryset(self):
        qs = super().get_queryset().filter(publish=True)
        if self.request.LANGUAGE_CODE == 'en':
            qs = qs.filter(lang='en')
        else:
            qs = qs.filter(lang='tr')
        return qs


class InfographicDetailView(DetailView):
    model = Infographic

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(publish=True)

jinac/people/views.py
from django.db.models import Max, F
from django.views.generic import ListView, DetailView
from jinac.people.models import Journalist

qs = Journalist.objects.all()
class JournalistListView(ListView):
    model = Journalist

    def get_queryset(self):
        qs = super().get_queryset()
        qs = qs.filter(publish=True).exclude(short_bio__isnull=True).exclude(photo__isnull=True).\
            exclude(short_bio='').exclude(photo='')
        if self.request.LANGUAGE_CODE == 'en':
            qs = qs.exclude(bio_en__isnull=True).exclude(bio_en='')
        if self.request.GET.get('f'):
            qs = qs.filter(name__istartswith=self.request.GET.get('f'))
        if self.request.GET.get('s'):
            status = self.request.GET.get('s')
            qs = qs.filter(
                journaliststatus__end_date__isnull=True
            ).annotate(status=F('journaliststatus__status')).annotate(
                last_date=Max('journaliststatus__start_date')
            ).filter(journaliststatus__start_date=F('last_date'))
            if status == 'jailed':
                qs = qs.filter(status__in=[3, 4, 8])
            elif status == 'prosecuted':
                qs = qs.filter(status__in=[1, 3, 5, 8])
            elif status == 'pending':
                qs = qs.filter(status=1)
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'filter': self.request.GET.get('f')
        })
        return context


class JournalistDetailView(DetailView):
    model = Journalist

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(publish=True)

jinac/templates/cases/case_detail.html
{% extends 'base.html' %}
{% load i18n staticfiles humanize martortags %}


{% block content %}

<div class="container">

    <h2 class="mt-4">
        {% if case.name_en and LANGUAGE_CODE == 'en' %}
            {{ case.name_en }}
        {% else %}
            {{ case.name }}
        {% endif %}
    </h2>


    {% with case.casedocument_set.all as case_documents %}
    {% with case.get_journalists as case_journalists %}

    <div class="row">

      <div class="col-md-9">

        <ul class="nav nav-tabs">
          <li class="nav-item">
            <a class="nav-link active" data-toggle="tab" data-target="#kunye-{{ case.id }}" style="color:black;">{% if LANGUAGE_CODE == 'tr' %}{% trans "Case Summary" %}{% else %}Trial Summary{% endif %}</a>
          </li>
          {% for note in case.notes %}
            <li class="nav-item">
                <a class="nav-link {% if forloop.first %}active{% endif %}" data-toggle="tab" data-target="#tab-note{{ note.id }}" role="tab">
                {% if LANGUAGE_CODE == 'en' %}
                    {{ note.type_en }}
                {% else %}
                    {{ note.type }}
                {% endif %}
                </a>
            </li>
          {% endfor %}
        </ul>

        <div class="card card-tabs-1">
          <div class="card-block">
            <div class="tab-content">

              <div id="kunye-{{ case.id }}" class="tab-pane active">
                  <p>
                  {% if case.summary_en and LANGUAGE_CODE == 'en' %}
                      {{ case.summary_en|safe_markdown }}
                  {% elif case.summary and LANGUAGE_CODE == 'tr' %}
                      {{ case.summary|safe_markdown }}
                  {% endif %}
                  </p>
              </div>

              {% for note in case.notes %}
              <div class="tab-pane {% if forloop.first %}active{% endif %}" id="tab-note{{ note.id }}">
              {% if LANGUAGE_CODE == 'en' and note.note_en %}
                {{ note.note_en|safe_markdown }}
              {% else %}
                {{ note.note|safe_markdown }}
              {% endif %}
              </div>
              {% endfor %}


            </div>
          </div>
        </div>


      </div>


      <div class="col-md-3">

          {% if LANGUAGE_CODE != 'en' %}
              {% if case.trial_set.all %}
                <h5 class="mt-4">
                    {% trans "Trial Reports" %}
                </h5>
                {% for trial in case.trial_set.all reversed %}

                    <a href="{{ trial.get_absolute_url }}" class="d-block">
                        {{ trial.session_no }}. {% trans "Standing" %}
                        -
                        {{ trial.time_start|date }}
                    </a>

                {% endfor %}
              {% endif %}
          {% endif %}

          {% if case_documents or case.trial_documents %}
            <h5 class="mt-4">
                {% trans "Documents" %}
            </h5>

              {% for doc in case_documents %}
                  <p>
                      {% if doc.type %}
                          {% if LANGUAGE_CODE == 'en' and doc.type.type_en %}
                              <a href="{{ doc.file.url }}" target="_blank">{{ doc.type.type_en }}</a>
                          {% else %}
                              <a href="{{ doc.file.url }}" target="_blank">{{ doc.type }}</a>
                          {% endif %}
                      {% else %}
                          <a href="{{ doc.file.url }}" target="_blank">{% trans "Download" %}</a>
                      {% endif %}
                  </p>
              {% endfor %}

              {% for doc in case.trial_documents %}
                  <p>
                      {{ doc.trial.session_no }}. {% trans "Standing" %}
                      {% if doc.type %}
                          {% if LANGUAGE_CODE == 'en' and doc.type.type_en %}
                              (<a href="{{ doc.file.url }}" target="_blank">{{ doc.type.type_en }}</a>)
                          {% else %}
                              (<a href="{{ doc.file.url }}" target="_blank">{{ doc.type }}</a>)
                          {% endif %}
                      {% else %}
                          <a href="{{ doc.file.url }}" target="_blank">{% trans "Download" %}</a>
                      {% endif %}
                  </p>
              {% endfor %}

          {% endif %}

          {% if case_journalists %}
            <h5 class="mt-4">
                {% trans "Journalists" %}
            </h5>

              {% for case_journalist in case_journalists %}
                  {% with case_journalist.journalist as other_journalist %}
                      {% if journalist != other_journalist %}
                          <a href="{{ other_journalist.get_absolute_url }}" class="d-block">{{ other_journalist.name }}</a>
                      {% endif %}
                  {% endwith %}
              {% endfor %}

          {% endif %}


      </div>

    </div>




          {% endwith %}
          {% endwith %}

</div>

{% endblock %}

jinac/templates/cases/case_list.html
{% extends 'base.html' %}
{% load i18n staticfiles martortags %}

{% get_current_language as LANGUAGE_CODE %}

{% block content %}

<div class="container">


    <div class="row justify-content-md-center mt-4 mb-5" style="min-width:80%; float:none;">
        <div class="gazeteciler-top text-center">
            <a href="?f=" class="btn btn-sm btn-outline-secondary {% if not filter %}text-white btn-secondary{% endif %}">{% trans "All" %}</a>
            {% for c in "ABCÇDEFGHIİJKLMNOÖPRSŞTUÜVYZ" %}
                <a class="btn btn-sm btn-outline-secondary {% if filter == c %}text-white btn-secondary{% endif %}" href="?f={{ c }}">{{ c }}</a>
            {% endfor %}
        </div>
    </div>



      {% for case in case_list %}

          <a name="{{ case.id }}"></a>

          <h4 class="mt-4">
            {% if case.name_en and LANGUAGE_CODE == 'en' %}
                {{ case.name_en }}
            {% else %}
                {{ case.name }}
            {% endif %}
          </h4>


          {% with case.casedocument_set.all as case_documents %}
          {% with case.journalists.all as case_journalists %}


          {% if case_journalists %}
          <div class="my-3">
              {% for case_journalist in case_journalists %}
                  {% with case_journalist.journalist as other_journalist %}
                      {% if journalist != other_journalist %}
                          <a href="{{ other_journalist.get_absolute_url }}" target="_blank">{{ other_journalist.name }}</a>{% if not forloop.last %}, {% endif %}
                      {% endif %}
                  {% endwith %}
              {% endfor %}
          </div>
          {% endif %}


          {% comment %}
          <p>
          {% if case.summary_en and LANGUAGE_CODE == 'en' %}
              {{ case.summary_en|safe_markdown|truncatewords_html:50 }}
          {% elif case.summary and LANGUAGE_CODE == 'tr' %}
              {{ case.summary|safe_markdown|truncatewords_html:50 }}
          {% endif %}
          </p>
          {% endcomment %}



          {% if case_documents %}

          <h6>{% trans "Documents" %}</h6>

          <ul>
              {% for doc in case_documents %}
                  <li>
                      {% if doc.type %}
                          {% if doc.type.type_en and LANGUAGE_CODE == 'en' %}
                              <a href="{{ doc.file.url }}" target="_blank">{{ doc.type.type_en }}</a>
                          {% elif case.summary and LANGUAGE_CODE == 'tr' %}
                              <a href="{{ doc.file.url }}" target="_blank">{{ doc.type }}</a>
                          {% endif %}
                      {% else %}
                          <a href="{{ doc.file.url }}" target="_blank">{% trans "Download" %}</a>
                      {% endif %}
                  </li>
              {% endfor %}

              {% for doc in case.trial_documents %}
                  <li>
                      {{ doc.trial.session_no }}. {% trans "Standing" %}
                      {% if doc.type %}
                          {% if doc.type.type_en and LANGUAGE_CODE == 'en' %}
                              <a href="{{ doc.file.url }}" target="_blank">{{ doc.type.type_en }}</a>
                          {% elif case.summary and LANGUAGE_CODE == 'tr' %}
                              <a href="{{ doc.file.url }}" target="_blank">{{ doc.type }}</a>
                          {% endif %}
                      {% else %}
                          <a href="{{ doc.file.url }}" target="_blank">{% trans "Download" %}</a>
                      {% endif %}
                  </li>
              {% endfor %}
          </ul>
          {% endif %}


          {% endwith %}
          {% endwith %}

          <a href="{{ case.get_absolute_url }}" target="_blank">{% trans "details" %} &raquo;</a>

          <br>
          <br>

      {% endfor %}

</div>

{% endblock %}


{% block foot %}

<script>

// tab üzerine ikinci kez tıklayınca tab'ı kapat

$('[data-toggle=tab]').click(function(){
    console.log($(this).hasClass('active'));
    if ($(this).hasClass('active')){
        var tab = $(this).data('target').substring(1);
        console.log(tab);
        $(this).removeClass('active');
        $('#'+ tab).removeClass('active').removeClass('show');
        return false;
    }
});

</script>

{% endblock %}

jinac/templates/cases/trial_detail.html
{% extends 'base.html' %}
{% load i18n staticfiles humanize martortags %}


{% block content %}

<div class="container">

          <h2 class="mt-4">
            {% if trial.case.name_en and LANGUAGE_CODE == 'en' %}
                {{ trial.case.name_en }}
            {% else %}
                {{ trial.case.name }}
            {% endif %}
              <small class="float-right">
                  <a href="{{ trial.case.get_absolute_url }}" class="small">{% trans "case details" %} &raquo;</a>
              </small>
          </h2>

            <h3 class="mt-2">
                {{ trial.session_no }}. {% trans "Standing" %}
                -
                {{ trial.time_start|date }}
            </h3>

            {% with trial.trialdocument_set.all as trial_documents %}

                <div class="tab-content">
                    <div class="col-md-12 px-3">
                        <div class="container flex-container">

                            <ul class="nav nav-tabs" id="myTab" style="font-size:13px; align-content: justify; padding-top:1%;">
                                {% for note in trial.notes %}
                                    <li class="nav-item">
                                        <a class="nav-link {% if forloop.first %}active{% endif %}" data-toggle="tab" data-target="#note{{ note.id }}" style="color:black;">{{ note.type }}</a>
                                    </li>
                                {% endfor %}

                                {% if trial_documents %}
                                    <li class="nav-item">
                                        <a class="nav-link" data-toggle="tab" data-target="#docs-{{ trial.id }}" style="color:black;">{% trans "Documents" %}</a>
                                    </li>
                                {% endif %}

                            </ul>

                            <div class="tab-content">

                                {% for note in trial.notes %}
                                    <div id="note{{ note.id }}" class="tab-pane fade {% if forloop.first %}show active{% endif %}">
                                        <p>
                                            <br/>
                                            {{ note.note|safe_markdown }}
                                        </p>
                                    </div>
                                {% endfor %}

                                {% if trial_documents %}
                                    <div id="docs-{{ trial.id }}" class="tab-pane fade ">
                                        <p>
                                        {% for trial_document in trial_documents %}
                                            <br/>
                                            <a href="{{ trial_document.file.url }}" target="_blank">{% if trial_document.type %}{{ trial_document.type }}{% else %}{{ trial_document.file.name }}{% endif %}</a>
                                        {% endfor %}
                                        </p>
                                    </div>
                                {% endif %}

                            </div>
                        </div>
                    </div>
                </div>

            {% endwith %}

</div>

{% endblock %}